apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quickfix-server.fullname" . }}-config
data:
  server.cfg: |-
    [default]
    ConnectionType=acceptor
    SocketAcceptPort=9880
    StartTime=00:00:00
    EndTime=00:00:00
    HeartBtInt=30
    ValidOrderTypes=1,2,F
    SenderCompID=*
    SenderSubID=*
    SenderLocationID=*
    TargetCompID=*
    TargetSubID=*
    TargetLocationID=*
    UseDataDictionary=Y
    DefaultMarketPrice=15
    JdbcDriver=com.mysql.cj.jdbc.Driver
    JdbcURL=jdbc:mysql://{{ .Release.Name }}-mysql:3306/quickfix
    JdbcUser={{ .Values.mysql.auth.username }}
    JdbcPassword={{ .Values.mysql.auth.password }}
    JdbcLogHeartBeats=N
    JdbcStoreMessagesTableName=messages
    JdbcStoreSessionsTableName=sessions
    JdbcLogEventTable=event_log
    JdbcLogIncomingTable=messages_log
    JdbcLogOutgoingTable=messages_log
    ResetOnLogon=N
    ResetOnLogout=N
    ResetOnDisconnect=N
    SendRedundantResendRequests=N
    [session]
    AcceptorTemplate=Y
    BeginString=FIX.4.4
