version: "3.9"
services:
  server:
    build:
      context: ./server-dynamic-sessions-database/.
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n -Xmx512m -Xms512m -Dspring.profiles.active=docker"
      QUICKFIXJ_SERVER_CONFIG_FILE: "file:/opt/app/server.cfg"
    volumes:
      - ./configs/server.cfg:/opt/app/server.cfg
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - net

  mysql:
    image: mysql/mysql-server:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: quickfix
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    volumes:
      - mysql-server-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - net


  client-1:
    build:
      context:  ./simple-client/.
      dockerfile: ./Dockerfile
    environment:
      QUIICKFIXJ_CLIENT_CONFIG_FILE: "file:/opt/app/quickfixj-client.cfg"
    volumes:
      - ./configs/quickfixj-client-1.cfg:/opt/app/quickfixj-client.cfg
      - client-1-logs:/tmp/logs
      - client-1-data:/opt/app/target/data/banzai
    depends_on:
      server:
        condition: service_started
    networks:
      - net

  client-2:
    build:
      context:  ./simple-client/.
      dockerfile: ./Dockerfile
    environment:
      QUIICKFIXJ_CLIENT_CONFIG_FILE: "file:/opt/app/quickfixj-client.cfg"
    volumes:
      - ./configs/quickfixj-client-2.cfg:/opt/app/quickfixj-client.cfg
      - client-2-logs:/tmp/logs
      - client-2-data:/opt/app/target/data/banzai
    depends_on:
      server:
        condition: service_started
    networks:
      - net

volumes:
  mysql-server-data:
  client-1-logs:
  client-1-data:
  client-2-logs:
  client-2-data:

networks:
  net:
