name: Docker Image CI

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  GCR_REPO: ghcr.io/${{ github.repository_owner }}/quickfix-server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server-dynamic-sessions-database/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/on0t0le/quickfix-dynamic-session-database:latest

  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Helm package
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin
          helm package .helm/quickfix-server
          helm push quickfix-server-*.tgz ${{ env.GCR_REPO }}